/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI.
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

import (
	"time"
)

type Commit struct {
	AuthorDate time.Time `json:"author_date,omitempty"`

	AuthorEmail string `json:"author_email,omitempty"`

	AuthorLogin string `json:"author_login,omitempty"`

	AuthorName string `json:"author_name,omitempty"`

	Body string `json:"body,omitempty"`

	Branch string `json:"branch,omitempty"`

	Commit string `json:"commit,omitempty"`

	CommitUrl string `json:"commit_url,omitempty"`

	CommitterDate time.Time `json:"committer_date,omitempty"`

	CommitterEmail string `json:"committer_email,omitempty"`

	CommitterLogin string `json:"committer_login,omitempty"`

	CommitterName string `json:"committer_name,omitempty"`

	Subject string `json:"subject,omitempty"`
}
