/*
 * CircleCI API
 *
 * The CircleCI API is a fully-featured JSON API that allows you to access all information and trigger all actions in CircleCI.
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Project struct {
	Emails string `json:"emails,omitempty"`

	OnDashboard bool `json:"on_dashboard,omitempty"`
}
